# CMake generated Testfile for 
# Source directory: /Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test
# Build directory: /Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[zlib_example]=] "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/zlib_example.app/zlib_example")
set_tests_properties([=[zlib_example]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;20;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_static_example]=] "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/zlib_static_example.app/zlib_static_example")
set_tests_properties([=[zlib_static_example]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;67;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_install]=] "/opt/homebrew/bin/cmake" "--install" "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib" "--prefix" "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/test_install" "--config" "Release")
set_tests_properties([=[zlib_install]=] PROPERTIES  FIXTURES_SETUP "zlib_install" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;128;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_find_package_configure]=] "/opt/homebrew/bin/cmake" "-B/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_test_build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_C_FLAGS=" "-DCMAKE_INSTALL_PREFIX=/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/test_install" "--fresh" "-G" "Unix Makefiles" "-S/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_test")
set_tests_properties([=[zlib_find_package_configure]=] PROPERTIES  FIXTURES_REQUIRED "zlib_install" FIXTURES_SETUP "fp_config" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;172;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_find_package_build]=] "/opt/homebrew/bin/cmake" "--build" "." "--config" "Release")
set_tests_properties([=[zlib_find_package_build]=] PROPERTIES  FIXTURES_REQUIRED "fp_config" FIXTURES_SETUP "fp_build" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_test_build" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;182;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_find_package_test]=] "/opt/homebrew/bin/ctest" "-C" "Release")
set_tests_properties([=[zlib_find_package_test]=] PROPERTIES  ENVIRONMENT "CTEST_OUTPUT_ON_FAILURE=1" FIXTURES_REQUIRED "fp_build" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_test_build" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;187;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_find_package_no_components_configure]=] "/opt/homebrew/bin/cmake" "-B/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_no_components_test_build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_C_FLAGS=" "-DCMAKE_INSTALL_PREFIX=/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/test_install" "--fresh" "-G" "Unix Makefiles" "-S/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_no_components_test")
set_tests_properties([=[zlib_find_package_no_components_configure]=] PROPERTIES  FIXTURES_REQUIRED "zlib_install" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;207;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_find_package_wrong_components_configure]=] "/opt/homebrew/bin/cmake" "-B/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_wrong_components_test_build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_C_FLAGS=" "-DCMAKE_INSTALL_PREFIX=/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/test_install" "--fresh" "-G" "Unix Makefiles" "-S/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_wrong_components_test")
set_tests_properties([=[zlib_find_package_wrong_components_configure]=] PROPERTIES  FIXTURES_REQUIRED "zlib_install" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;231;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_add_subdirectory_configure]=] "/opt/homebrew/bin/cmake" "-B/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/add_subdirectory_test_build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_C_FLAGS=" "-DCMAKE_INSTALL_PREFIX=/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/test_install" "--fresh" "-G" "Unix Makefiles" "-S/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_test")
set_tests_properties([=[zlib_add_subdirectory_configure]=] PROPERTIES  FIXTURES_REQUIRED "zlib_install" FIXTURES_SETUP "as_config" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;250;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_add_subdirectory_build]=] "/opt/homebrew/bin/cmake" "--build" "." "--config" "Release")
set_tests_properties([=[zlib_add_subdirectory_build]=] PROPERTIES  FIXTURES_REQUIRED "as_config" FIXTURES_SETUP "as_build" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/add_subdirectory_test_build" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;260;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_add_subdirectory_test]=] "/opt/homebrew/bin/ctest" "-C" "Release")
set_tests_properties([=[zlib_add_subdirectory_test]=] PROPERTIES  ENVIRONMENT "CTEST_OUTPUT_ON_FAILURE=1" FIXTURES_REQUIRED "as_build" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/add_subdirectory_test_build" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;265;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_add_subdirectory_exclude_configure]=] "/opt/homebrew/bin/cmake" "-B/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/add_subdirectory_exclude_test_build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_C_FLAGS=" "-DCMAKE_INSTALL_PREFIX=/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/test_install" "--fresh" "-G" "Unix Makefiles" "-S/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/findpackage_test")
set_tests_properties([=[zlib_add_subdirectory_exclude_configure]=] PROPERTIES  FIXTURES_REQUIRED "zlib_install" FIXTURES_SETUP "asx_config" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;285;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_add_subdirectory_exclude_build]=] "/opt/homebrew/bin/cmake" "--build" "." "--config" "Release")
set_tests_properties([=[zlib_add_subdirectory_exclude_build]=] PROPERTIES  FIXTURES_REQUIRED "as_config" FIXTURES_SETUP "asx_build" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/add_subdirectory_exclude_test_build" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;295;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
add_test([=[zlib_add_subdirectory_exclude_test]=] "/opt/homebrew/bin/ctest" "-C" "Release")
set_tests_properties([=[zlib_add_subdirectory_exclude_test]=] PROPERTIES  ENVIRONMENT "CTEST_OUTPUT_ON_FAILURE=1" FIXTURES_REQUIRED "asx_build" WORKING_DIRECTORY "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/build-ios-device/zlib/test/add_subdirectory_exclude_test_build" _BACKTRACE_TRIPLES "/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;301;add_test;/Users/ombhardwaj/Development/projects/aiotool/imagecore/packages/core/third_party/zlib/test/CMakeLists.txt;0;")
